import { create } from '@storybook/theming/create';

export default create({
  appBg: 'white',
  appBorderColor: '#d8d8d8',
  appBorderRadius: 0,
  appContentBg: 'white',
  barBg: 'white',
  barSelectedColor: '#072caf',
  barTextColor: '#383838',
  base: 'light',
  brandImage: '/assets/images/alfacash-logo.svg',
  brandTitle: 'Alfa Ui Kit',
  brandUrl: 'https://app.zeplin.io/project/0000/dashboard',
  colorPrimary: '#072caf',
  colorSecondary: '#989eb7',
  fontBase: '"AvertaCY", sans-serif',
  fontCode: 'monospace',
  inputBg: 'white',
  inputBorder: '#d8d8d8',
  inputBorderRadius: 4,
  inputTextColor: '#383838',
  textColor: '#383838',
  textInverseColor: 'rgba(255,255,255,0.9)',
});
